const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Sprite,
		C3.Plugins.NinePatch,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Plugins.Tilemap,
		C3.Behaviors.jumpthru,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Behaviors.Sin,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Keyboard: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Audio: 0},
	{PlatformInfo: 0},
	{btnLeft: 0},
	{btnRight: 0},
	{btnUp: 0},
	{btnMenu: 0},
	{btnReset: 0},
	{btnSound: 0},
	{bg: 0},
	{Bullet: 0},
	{clouds: 0},
	{sun: 0},
	{Solid: 0},
	{bridge: 0},
	{carrot: 0},
	{coin: 0},
	{win: 0},
	{defeat: 0},
	{ScrollTo: 0},
	{game_manager: 0},
	{running: 0},
	{jumps: 0},
	{Platform: 0},
	{Tween: 0},
	{player: 0},
	{player_spr: 0},
	{Jumpthru: 0},
	{Tilemap: 0},
	{water: 0},
	{carrot_ui: 0},
	{coin2: 0},
	{transition: 0},
	{txtBtnNivel: 0},
	{name: 0},
	{txtUI: 0},
	{Variables: 0},
	{nHoja: 0},
	{selector_manager: 0},
	{btnArrowLeft: 0},
	{btnArrowRight: 0},
	{Nivel: 0},
	{Sine: 0},
	{btnNivel: 0},
	{Anchor: 0},
	{Game_Tittle: 0},
	{btnPlay: 0},
	{tutorial: 0},
	{tap_to_continue: 0},
	{bg_win: 0},
	{Explosion: 0},
	{masc_colision: 0},
	{bird: 0},
	{bird_dead: 0},
	{jumptime: 0},
	{currenttime: 0},
	{jumping: 0},
	{enemie1: 0},
	{enemie_dead: 0},
	{final: 0},
	{Buttons: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newLayer: 0},
	{LEVEL: 0},
	{double_jump: 0},
	{mag: 0},
	{dur: 0},
	{totStars: 0},
	{posX: 0},
	{posY: 0},
	{layer: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0},
	{SOUNDVOLUME: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	btnLeft: class extends self.ISpriteInstance {},
	btnRight: class extends self.ISpriteInstance {},
	btnUp: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnReset: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	bg: class extends self.IWorldInstance {},
	clouds: class extends self.ISpriteInstance {},
	sun: class extends self.ISpriteInstance {},
	bridge: class extends self.ISpriteInstance {},
	carrot: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	game_manager: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	player_spr: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	water: class extends self.ISpriteInstance {},
	carrot_ui: class extends self.ISpriteInstance {},
	coin2: class extends self.ISpriteInstance {},
	transition: class extends self.ISpriteInstance {},
	txtBtnNivel: class extends self.ISpriteFontInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	Variables: class extends self.IArrayInstance {},
	selector_manager: class extends self.ISpriteInstance {},
	btnArrowLeft: class extends self.ISpriteInstance {},
	btnArrowRight: class extends self.ISpriteInstance {},
	btnNivel: class extends self.ISpriteInstance {},
	nHoja: class extends self.ISpriteInstance {},
	Game_Tittle: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	tap_to_continue: class extends self.ISpriteInstance {},
	bg_win: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	masc_colision: class extends self.ISpriteInstance {},
	bird: class extends self.ISpriteInstance {},
	bird_dead: class extends self.ISpriteInstance {},
	enemie1: class extends self.ISpriteInstance {},
	enemie_dead: class extends self.ISpriteInstance {},
	final: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}